### ISSUE TITLE
Folder structure - Review + Recommendation needed

### ISSUE THREAD

**Issue by gh0stl0nely** [Toronto-Tech-Mentoring/TTM-Gatsby#28]
This is a diagram I drew that represents the basic folder structure of our current codebase. Let me know what you think.

Link to diagram: https://www.autodraw.com/share/GE9913USMGPH
Trello link: https://trello.com/c/oYu5WzzF

**Comment by harshvchawla** [comment]
I think this is nice and concise - from a glance I can see (and wonder( why is Partner page a separate node

Also, given that the diagram has text mostly - is that website (autodraw) editable when shared?
If not, we can use draw.io or MS Word type stuff too :p

**Comment by gh0stl0nely** [comment]
@harshvchawla Yeah I believe it is editable. Once you click on the link and press "start drawing", that should trigger a drawing panel for you to start editing. 

The reason I chose it is because it's the first thing it came up on my Google search hahaha. Happy to switch it to other tools if you guys think it makes life easier for us.

> I think this is nice and concise - from a glance I can see (and wonder( why is Partner page a separate node
> 
> Also, given that the diagram has text mostly - is that website (autodraw) editable when shared?
> If not, we can use draw.io or MS Word type stuff too :p

**Comment by harshvchawla** [comment]
When i click on start drawing, it opens a new sheet of paper for me :/
Even a simple tree with description might help e.g
```
Windows Powershell> tree
├───client
├───contact
├───partners
├───sponsors
└───volunteer
```
(tree is a linux cmd but I couldnt locate my cygwin install)
in that output, labelling what the significance is ok too (abstracting information, using color coding for labels, etc)

or just have the diagram u created in an editable form

Do whatever is easiest bcos this information will be consumed at a low frequency (but with a high impact :))

**Comment by gh0stl0nely** [comment]
Hmm that is weird because it is editable on my end.

Does this work ? @harshvchawla 

** Folder structure**
src
|--> components (contains folder that contain all the components that make up each page, 
|--> images (contains folder that contain image file (SVG) for each pages)
|--> layout (contains the navbar, the page (children component) and the footer) -> This component is shared across the site
|--> pages (contains the folder that has a index.js file that has a Main layout and the page body of each page)
|--> styles (contain css style file for the entire app)
|--> utils (@rishFilet  Can you add here?) 


** If you are looking for the layout of the website **
|--> Mainlayout.js (in layout/index.js)
            |-----> NavBar  (components/NavBar)
            |-----> Children (This is the page body) -> in (components/{Page_Name}) => {Page_Name} is like Home, Partner, 
            |-----> Footer (components/Footer)

**Comment by harshvchawla** [comment]
This is great @gh0stl0nely !
Presentation carries its brownie points always :p!
Acc to me, this piece of information can be moved from "issue" to "wiki" in github even

And looking at ur details, I could understand and reason/ponder - how come navbar and footer- part of layout, belong to components folder (being nitpicky, not that its in any manner incorrect as the way it is now)

**Comment by rishFilet** [comment]
> Hmm that is weird because it is editable on my end.
> 
> Does this work ? @harshvchawla
> 
> ** Folder structure**
> src
> |--> components (contains folder that contain all the components that make up each page,
> |--> images (contains folder that contain image file (SVG) for each pages)
> |--> layout (contains the navbar, the page (children component) and the footer) -> This component is shared across the site
> |--> pages (contains the folder that has a index.js file that has a Main layout and the page body of each page)
> |--> styles (contain css style file for the entire app)
> |--> utils (@rishFilet Can you add here?)
> 
> ** If you are looking for the layout of the website **
> |--> Mainlayout.js (in layout/index.js)
> |-----> NavBar (components/NavBar)
> |-----> Children (This is the page body) -> in (components/{Page_Name}) => {Page_Name} is like Home, Partner,
> |-----> Footer (components/Footer)

Yup i'll have a look at the diagram shortly and add to it but this is an awesome start! Thanks for also joining the convo on it @harshvchawla . I like what you said about it being low frequency but high impact, true statement in designing this. It helps any newbie or vet see what the structure is visually saving time sifting through the code.

I found some some other diagram programs in github (i like experimenting with open source first so we can contribute if we find bugs :). 

Def move to wiki.

**Comment by BBoutet1** [comment]
You can also keep the diagram with the folders name only, to keep the tree clean, and put the presentation or explanations in paragraphs on the bottom.

**Comment by rishFilet** [comment]
Closing this as an issue. See https://trello.com/c/reB70nqJ for the architecture and how to edit further
