### ISSUE TITLE
White spacing upon resizing city SVG 

### ISSUE THREAD

**Issue by gh0stl0nely** [Toronto-Tech-Mentoring/TTM-Gatsby#34]
@hanlinc27  If the screen is resized, there will be huge spacing here. 

![image](https://user-images.githubusercontent.com/23471813/94466204-0faed800-018f-11eb-9a35-f10ac89c2e79.png)

**Comment by BBoutet1** [comment]
This scrolling bar too is not consistent with the idea of responsive layout. It comes from the same section.

![image](https://user-images.githubusercontent.com/59809722/94484525-90c79880-01aa-11eb-8a8e-d411abfd79e7.png)

**Comment by gh0stl0nely** [comment]
> This scrolling bar too is not consistent with the idea of responsive layout. It comes from the same section.
> 
> ![image](https://user-images.githubusercontent.com/59809722/94484525-90c79880-01aa-11eb-8a8e-d411abfd79e7.png)

Possibly due to the Hero Text again. Probably will it up in todays optional meeting.

**Comment by rishFilet** [comment]
@gh0stl0nely @hanlinc27  Can you put a comment on how to reproduce this? This may be my code that i added to scale the image for responsiveness. Will take a :eyes:  if its the case or i can in general and comment what i found

**Comment by gh0stl0nely** [comment]
> @gh0stl0nely @hanlinc27 Can you put a comment on how to reproduce this? This may be my code that i added to scale the image for responsiveness. Will take a 👀 if its the case or i can in general and comment what i found

@rishFilet I think it only has to do with the HeroText component in the About us page since if commented out the problem disappears. Possibly one of the styling is off.

**Comment by gh0stl0nely** [comment]
Can be fixed with setting height to SVG to auto
