### ISSUE TITLE
Blue border when click on Burger menu

### ISSUE THREAD

**Issue by gh0stl0nely** [Toronto-Tech-Mentoring/TTM-Gatsby#47]
Click on burger menu you will always see "Client"'s border being blue

![image](https://user-images.githubusercontent.com/23471813/95689388-6a5c2100-0bde-11eb-8ebf-5aae57cbafc8.png)

**Comment by harshvchawla** [comment]
solved in https://github.com/Toronto-Tech-Mentoring/TTM-Gatsby/pull/65
