### ISSUE TITLE
Does anybody know why this file is here in the root folder?

### ISSUE THREAD

**Issue by gh0stl0nely** [Toronto-Tech-Mentoring/TTM-Gatsby#81]
It seems like there was a TimelineSection.js file added 14 days ago in the root folder. Is there a reason why its here? Can we delete?

![image](https://user-images.githubusercontent.com/23471813/96631988-0ffd4780-12e5-11eb-8599-39e1c9841ccc.png)

**Comment by rishFilet** [comment]
Confrim with @BBoutet1 
![image](https://user-images.githubusercontent.com/28996036/96659790-e4468580-1315-11eb-9826-9a6cb21cc718.png)

**Comment by BBoutet1** [comment]
@gh0stl0nely @rishFilet filed deleted. To preserve the code before modifications I pasted the file in the wrong place.
