### ISSUE TITLE
Delivery Partners page has wrong text

### ISSUE THREAD

**Issue by hanlinc27** [Toronto-Tech-Mentoring/TTM-Gatsby#84]
It should say:
_"Thank you for partnering with us...
The Accelerator Project is part of an ecosystem of programs aimed at addressing homelessness in Toronto. Our delivery partners help facilitate our programs, and provide wrap-around support to allow our clients to focus on learning tech skills and building their futures."_

It currently says:
_"Thank you for partnering with us...
The Accelerator Project is an entirely volunteer-run organization. All donations go directly into offering tech mentoring to young people who have faced adversity."_

**Comment by airshiprook** [comment]
Fixed: https://github.com/Toronto-Tech-Mentoring/TTM-Gatsby/pull/85
