### ISSUE TITLE
Images rendering poorly on Mobile

### ISSUE THREAD

**Issue by hanlinc27** [Toronto-Tech-Mentoring/TTM-Gatsby#9]
![image](https://user-images.githubusercontent.com/19617248/93128999-5cc68080-f69e-11ea-8def-925e641d2fa7.png)
Image quality is low on mobile and when zoomed in on web.
Consider:

- exporting as SVG vs. PNG directly from the Figma

**Comment by gh0stl0nely** [comment]
@hanlinc27 I think this is resolved. Could you check one more time and close out the issue?

**Comment by airshiprook** [comment]
Theres still 2 assets that need to be switched over to SVG. The logo and heart.

**Comment by gh0stl0nely** [comment]
> Theres still 2 assets that need to be switched over to SVG. The logo and heart.

@BBoutet1 Can you fix the logo for the navbar?

**Comment by BBoutet1** [comment]
Sure

**Comment by hanlinc27** [comment]
I'm going to close this issue. The heart itself's sizing issue is another problem and we're changing the logo anyways (+the quality was already poor when I got it from the gdrive to put it into the figma design).
